name: CI

on: [push, pull]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update submodules
      run: |
        git submodule foreach git pull origin master
